# NumPy - Ejercicios

### 1. Crea una matriz 3x3 con valores entre 0 y 8.

In [9]:
import numpy as np

array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. Crea una matriz 5x5 con los valores 1,2,3,4 debajo de la diagonal principal.

In [12]:
array_identidad= np.eye(5, k=-1)
array_identidad[2,1]=2
array_identidad[3,2]=3
array_identidad[4,3]=4
array_identidad

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [15]:
matriz = np.zeros((5,5))
matriz[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
matriz

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [17]:
array_1 = np.eye(5, k=-1)
array_2 = np.array([1,2,3,4,0])
array_3 = array_1 * array_2
array_3

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [16]:
array_1 = np.eye(5, k = -1)
array_1[array_1 == 1] = [1,2,3,4]
array_1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [ ]:
array_identidad= np.eye(5, k=-1)
array_identidad[2]=array_identidad[2] * 2
array_identidad[3]=array_identidad[3]*3
array_identidad[3]=array_identidad[4]*4
array_identidad

In [13]:
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 3. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [20]:
def array_ex_3(n):
    array_ex_3 = np.eye(n)
    array_ex_3[array_ex_3 == 0] = n 
    
    return  array_ex_3

print(array_ex_3(5))

[[1. 5. 5. 5. 5.]
 [5. 1. 5. 5. 5.]
 [5. 5. 1. 5. 5.]
 [5. 5. 5. 1. 5.]
 [5. 5. 5. 5. 1.]]


In [22]:
def ejercicio_3(n):
    matriz = np.ones((n,n)) * n
    np.fill_diagonal(matriz,1)
    return (matriz)
ejercicio_3(5)

array([[1., 5., 5., 5., 5.],
       [5., 1., 5., 5., 5.],
       [5., 5., 1., 5., 5.],
       [5., 5., 5., 1., 5.],
       [5., 5., 5., 5., 1.]])

In [23]:
def ejercicio_3(n):
    matriz = np.ones((n,n)) * n
    matriz = matriz - np.identity(n)*(n-1)
    return matriz

ejercicio_3(5)

array([[1., 5., 5., 5., 5.],
       [5., 1., 5., 5., 5.],
       [5., 5., 1., 5., 5.],
       [5., 5., 5., 1., 5.],
       [5., 5., 5., 5., 1.]])

In [2]:
import numpy as np

### 4. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [3]:
def matriz(n,m, traspuesta):
    matriz_1=np.arange(0,n*m)
    matriz_2=matriz_1.reshape(n,m)
    if traspuesta:
        return matriz_2.T
    else:
        return matriz_2
    
matriz(4,5,False)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 5. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [8]:
def doble_array (array1, array2):
    array3 = np.empty_like(array1) # np.empty(array1.shape)
    array3[array1 > array2] = 1
    array3[array1 <= array2] = 0
    return array3

doble_array (np.array([[3,5],[2,2]]), np.array([[2,2],[8,8]]))

array([[1, 1],
       [0, 0]])

In [ ]:
def doble_array (array1, array2):
    array3 = np.zeros_like(array1) # np.zeros(array1.shape)
    array3[array1 > array2] = 1
    return array3


In [9]:
def ejercicio5(array_1,array_2):
    array_3=array_1>array_2
    array_4=np.array(array_3, dtype=np.int8)
    return array_4

### 6. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [11]:
def filasfinal(array,tupla_filas):
    n,m = array.shape
    lista_filas = list(tupla_filas)
    if max(lista_filas) > n:
        return ('La tupla tiene algún índce mayor que el número de filas')
    else:
        lista_filas_final = [- fila for fila in lista_filas]
        return(array[lista_filas_final])
    
array = np.random.randn(8,4)
tupla = (5,3,6)
print(array)
filasfinal(array,tupla)

[[-1.57759398 -1.81286255  2.99780851 -0.09115207]
 [-0.11539132  1.17114408  0.53318104 -0.16539265]
 [-1.13773899  0.94320294  0.5636784  -0.3592956 ]
 [-1.15636182  0.76753663  0.54604084  0.68437726]
 [ 0.48875272  0.37858245  0.74001313  0.85257251]
 [-0.72356253 -1.46022264 -1.03207395  1.27874088]
 [-1.14776473  0.13525921 -0.13950328 -0.29280242]
 [-0.05340892  0.31454825  1.44982422 -1.08944671]]
[-5, -3, -6]


array([[-1.15636182,  0.76753663,  0.54604084,  0.68437726],
       [-0.72356253, -1.46022264, -1.03207395,  1.27874088],
       [-1.13773899,  0.94320294,  0.5636784 , -0.3592956 ]])

### 7. Replica la función del ejercicio 5 utilizando la función np.where

In [13]:
def ejercicio_7(array5_1, array5_2):
    return np.where(array_5_1 > array_5_2, 1,0)

array_5_1 = np.random.randn(4,4)
array_5_2 = np.random.randn(4,4)
ejercicio_7(array_5_1,array_5_2)

array([[1, 0, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 0]])

### 8. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [33]:
def ejercicio_8(array_8):
    if (array_8 < 0).sum() != 0: #np.sum(array_8 < 0)
        return "Hay un valor negativo"
    else:
        return "No hay un valor negativo"
    
def ejercicio_8(array_8):
    if (array_8 < 0).any(): #np.sum(array_8 < 0)
        return "Hay un valor negativo"
    else:
        return "No hay un valor negativo"
    
    
def ejercicio_8(array_8):
    return (array_8 < 0).any()

array_8 = np.random.randn(4,4)
ejercicio_8(array_8)

True

### 9. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [23]:
def funcion(a):
    if ejercicio_8(a):
        b = np.where(a<0,np.abs(a),0) 
        return np.sum(b) 
         
    else:
        return 'No hay negativos'
    
funcion(np.array([0,3,-4,-1,9]))

def funcion(a):
    if ejercicio_8(a):
        return -np.sum(array[array < 0])
         
    else:
        return 'No hay negativos'

5

### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [ ]:
def union(array1, array2):
    return np.union1d(array1,array2)

### 11. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [41]:
def descriptivos(nombres,numerico,nombre):
    if nombre not in nombres:
        return "El nombre no existe"
    else:
        num_col = numerico.shape[1]
        if num_col != nombres.size:
            return "Los tamaños de los arrays no coinciden"
        else:
            nombre_selec= numerico[:, nombres==nombre] #numerico.T[nombres==nombre]
            datos=(np.min(nombre_selec),np.max(nombre_selec),np.median(nombre_selec),np.mean(nombre_selec),np.std(nombre_selec))
            return datos

nombres_ej=np.array(["a","b","c","d"])
numerico_ej=np.random.randn(8,4)
nombre_ej="a"

descriptivos(nombres_ej,numerico_ej,nombre_ej)


(-1.2248285355325208, 1.229659988262854, 0.01892412209714324, 0.08538476439638658, 0.7123988849157867)
