# NumPy - Ejercicios (II)

In [3]:
import numpy as np

### 1. Crea una función que reciba un número n, genere una matriz nxn a partir de una secuencia numérica y escriba la misma en un fichero cuyo nombre se recibirá también como parámetro. Hazlo con ficheros binarios.

In [6]:
def matriz(n, nombre):
    array = np.arange(n*n).reshape(n,n)
    np.save(nombre, array)
    return array
matriz(5, 'Afi')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 2. Crea una función que reciba el nombre de un fichero binario de NumPy, lo lea como binario, sume el contenido del mismo por filas y guarde el resultado en un fichero de texto con el mismo nombre (pero extensión txt).

In [ ]:
def ejercicio(nombre_fichero):
    array1=np.load(nombre_fichero) #nombre_fichero + '.npy'
    array_suma=np.sum(array1, axis=1)
    np.savetxt(nombre_fichero[:-4]+'.txt', array_suma)  #nombre_fichero + '.txt'
    
ejercicio('Afi.npy')    

### 3. Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto escalar de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [8]:
def ejercicio3 (n,m):
    array1= np.random.randn(n*m).reshape(n,m) #np.random.randn(n,m)
    array2=np.random.randn(n*m).reshape(m,n)
    array3=np.dot(array1,array2)
    return(array1,array2,array3)
ejercicio3(4,5)




(array([[-0.22144017, -0.19131282,  0.38546753, -0.66182299,  0.58461619],
        [ 0.34177491, -1.02485124,  0.4242885 , -0.24112764,  1.45405979],
        [-0.12580503, -0.49743298, -0.96281998,  0.10850815,  0.16914766],
        [-2.09452969, -0.50267644, -1.83771793, -0.24177161,  0.91818074]]),
 array([[-0.13182475,  1.49002824,  0.31608099, -1.01483055],
        [-0.46200227, -2.6782496 , -0.3957459 , -2.91834713],
        [-1.51382795,  1.93842207, -0.67281845, -1.05838471],
        [-0.56681263, -0.09815837, -0.53643291,  0.26314282],
        [ 0.15264775, -0.4157587 , -0.28627338,  1.35355565]]),
 array([[-1.58329095e-03,  7.51534338e-01, -6.59678527e-02,
          9.92225104e-01],
        [ 1.44762564e-01,  3.49564258e+00, -5.87697136e-02,
          4.09966745e+00],
        [ 1.66825939e+00, -8.02530468e-01,  6.98265713e-01,
          2.85589074e+00],
        [ 3.56753470e+00, -5.69489815e+00,  6.40185203e-01,
          6.71677789e+00]]))

### 4. Crea una función que reciba una matriz de datos y un entero n y devuelva una muestra (muestreo aleatorio simple) de n elementos.

In [11]:
def fun_ex4 (array,a):
    n,m=array.shape
    list_ex4 = []
    i=0
    while i<a:
        elemento = array[np.random.randint(0,n), np.random.randint(0,m)]
        list_ex4.append(elemento)
        i+=1
    return list_ex4
array1=np.arange(9).reshape(3,3)
fun_ex4 (array1,5)





[3, 3, 4, 3, 3]

In [15]:
def muestreo(matriz,n):
    a,b = matriz.shape
    muestreo_filas = np.random.randint(0,a,n)
    print(muestreo_filas)
    muestreo_columnas = np.random.randint(0,b,n)
    print(muestreo_columnas)
    muestra = matriz[muestreo_filas,muestreo_columnas]
    return(muestra)

mat = np.random.randn(4,5)
print(mat)
muestreo(mat,50)

[[-0.01936582  0.48906414 -1.24214273 -0.78001258  1.77402278]
 [-0.93670006 -0.91937625  0.74154219 -0.69050341  0.99347612]
 [-0.86079045 -0.4830283   1.24496624 -0.25878635 -0.43274072]
 [ 0.56144471  0.2968298  -0.19883494  0.40690294  0.03912759]]
[2 3 3 2 2 2 2 3 2 0 1 0 3 3 2 0 2 3 0 0 2 3 2 3 3 0 1 2 0 2 3 2 1 3 1 3 1
 2 0 3 0 2 3 2 3 3 1 2 0 2]
[4 3 0 4 4 1 3 3 2 1 1 0 0 2 4 4 0 0 4 2 4 1 2 0 1 2 3 4 3 2 4 3 3 4 1 3 3
 4 4 3 4 2 3 1 1 0 4 3 0 2]


array([-0.43274072,  0.40690294,  0.56144471, -0.43274072, -0.43274072,
       -0.4830283 , -0.25878635,  0.40690294,  1.24496624,  0.48906414,
       -0.91937625, -0.01936582,  0.56144471, -0.19883494, -0.43274072,
        1.77402278, -0.86079045,  0.56144471,  1.77402278, -1.24214273,
       -0.43274072,  0.2968298 ,  1.24496624,  0.56144471,  0.2968298 ,
       -1.24214273, -0.69050341, -0.43274072, -0.78001258,  1.24496624,
        0.03912759, -0.25878635, -0.69050341,  0.03912759, -0.91937625,
        0.40690294, -0.69050341, -0.43274072,  1.77402278,  0.40690294,
        1.77402278,  1.24496624,  0.40690294, -0.4830283 ,  0.2968298 ,
        0.56144471,  0.99347612, -0.25878635, -0.01936582,  1.24496624])

In [18]:
def ejercicio_4(matriz,numero):
    muestra = []
    elementos = matriz.reshape(matriz.size)
    while len(muestra) < numero:
        i = np.random.randint(0,matriz.size)
        muestra.append(elementos[i])
    return (muestra)

ejercicio_4(mat,10)

[-0.1988349409238262,
 -1.2421427268525778,
 0.039127589293051136,
 0.5614447063173421,
 1.2449662431291246,
 0.4890641404932917,
 0.4069029386165109,
 -0.9193762511940359,
 -0.7800125750184582,
 -0.9193762511940359]

In [21]:
def ejercicio_4(matriz,numero):
    print(matriz)
    elementos = matriz.reshape(matriz.size)
    print(elementos)
    m = np.random.randint(0,matriz.size,numero)
    print(m)
    muestra = elementos[m]
    return muestra

ejercicio_4(mat,10)

[[-0.01936582  0.48906414 -1.24214273 -0.78001258  1.77402278]
 [-0.93670006 -0.91937625  0.74154219 -0.69050341  0.99347612]
 [-0.86079045 -0.4830283   1.24496624 -0.25878635 -0.43274072]
 [ 0.56144471  0.2968298  -0.19883494  0.40690294  0.03912759]]
[-0.01936582  0.48906414 -1.24214273 -0.78001258  1.77402278 -0.93670006
 -0.91937625  0.74154219 -0.69050341  0.99347612 -0.86079045 -0.4830283
  1.24496624 -0.25878635 -0.43274072  0.56144471  0.2968298  -0.19883494
  0.40690294  0.03912759]
[13  3 11  8 16 11  5  0  0 13]


array([-0.25878635, -0.78001258, -0.4830283 , -0.69050341,  0.2968298 ,
       -0.4830283 , -0.93670006, -0.01936582, -0.01936582, -0.25878635])